# Generated by Django 3.2.7 on 2021-09-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210908_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relations',
            options={'ordering': ['-is_main'], 'verbose_name': 'Тема статьи', 'verbose_name_plural': 'Темы статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='scopes', through='articles.Relations', to='articles.Scope', verbose_name='Темы статьи'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.scope', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
