# Generated by Django 3.1.2 on 2021-09-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210912_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-tag'], 'verbose_name': 'Тема статьи', 'verbose_name_plural': 'Темы статьи'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='title',
            new_name='tag',
        ),
    ]
