# Generated by Django 3.1.2 on 2021-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210912_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relation',
        ),
        migrations.AddField(
            model_name='scope',
            name='relation',
            field=models.ManyToManyField(related_name='scopes', through='articles.Relationship', to='articles.Article', verbose_name='Темы статьи'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
