# Generated by Django 3.1.2 on 2021-09-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210922_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-name'], 'verbose_name': 'Тема статьи', 'verbose_name_plural': 'Темы статьи'},
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='scopes',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='name',
        ),
    ]
