# Generated by Django 3.1.2 on 2021-09-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210922_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='relation',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Article', verbose_name='Темы статьи'),
        ),
    ]
